### ISSUE TITLE
Provide ES5 compatible package

### ISSUE THREAD

**Issue by damienix** [helpers/handlebars-utils#1]
Because of the line:
https://github.com/helpers/handlebars-utils/blob/1139e4f427379e0f34c1186926ca0c0a9430ed05/index.js#L136
you are required to add a special rule for Webpack like this:

    {
        test: /node_modules\/handlebars-utils\/index\.js$/,
        loader: "babel-loader",
        query: {presets: ["es2015"]}
    },

(usually people have `/node_modules` excluded from transpilation)

It would be nice to have it working out of the box so there are 2 solutions.

1. Remove this string interpolation (that's the only case it's used) AND don't use ES6 in the future
2. Provide the transpiled bundle.js in NPM package

It solution 1. looks good, I'd be happy to provide pull request for that :)

**Comment by jonschlinkert** [comment]
agreed, a pr for `1` would be great, thanks!

**Comment by damienix** [comment]
Take a look at the https://github.com/helpers/handlebars-utils/pull/2 and let me know when it's released, pretty please :)

**Comment by mattbrun** [comment]
👍 for this, otherwise pages break on IE11.

**Comment by damienix** [comment]
@jonschlinkert could you merge and release this?
